// components/RoadmapClient.tsx
"use client"
import { useEffect, useRef, useState } from "react";
import { useSession, signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import jsPDF from "jspdf";
// adjust these paths if your project aliases differ
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/src/components/ui/accordion";
import useRoadmaps from "@/app/api/hooks/useRoadmaps";

type RoadmapStep = { phase: string; skills: string[] };
type Resource = { title: string; url: string };

export default function RoadmapClient() {
  const { data: session } = useSession();
  const router = useRouter();
  const searchParams = useSearchParams();

  const [goal, setGoal] = useState("");
  const [skills, setSkills] = useState("");
  const [roadmap, setRoadmap] = useState<RoadmapStep[]>([]);
  const [loading, setLoading] = useState(false);
  const [resources, setResources] = useState<Record<string, Resource[]>>({});
  const [roadmapName, setRoadmapName] = useState("");
  const [saving, setSaving] = useState(false);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);

  const [expanded, setExpanded] = useState<string | null>(null);

  const { addRoadmap, refresh } = useRoadmaps();
  const autoGeneratedRef = useRef(false);

  const normalizeSkills = (s: string | null) =>
    (s || "")
      .split(",")
      .map((x) => x.trim())
      .filter(Boolean)
      .join(",");

  const generateRoadmap = async (overrideGoal?: string, overrideSkills?: string) => {
    const role = overrideGoal ?? goal;
    const skillsParam = overrideSkills ?? skills;
    if (!role) return;
    setLoading(true);
    setRoadmap([]);
    setResources({});
    try {
      const res = await fetch("/api/roadmap", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ role, skills: skillsParam }),
      });
      const data = await res.json();
      if (res.ok && Array.isArray(data?.roadmap?.phases)) {
        const structured = data.roadmap.phases.map((phase: any) => ({
          phase: phase.name || "Phase",
          skills: Array.isArray(phase.milestones) ? phase.milestones : [],
        }));
        setRoadmap(structured);

        // fetch resources per milestone (fire-and-forget)
        structured.forEach((phase: RoadmapStep) => {
          phase.skills.forEach(async (milestone: string) => {
            try {
              const r = await fetch(`/api/resources?query=${encodeURIComponent(milestone)}`);
              const json = await r.json();
              const vids = json?.resources ?? [];
              setResources((prev) => ({ ...prev, [milestone]: vids }));
            } catch (e) {
              console.warn("Resource fetch failed for:", milestone, e);
            }
          });
        });
      } else {
        const text = typeof data === "string" ? data : JSON.stringify(data, null, 2);
        setRoadmap([{ phase: "Roadmap", skills: text.split("\n").filter(Boolean) }]);
      }
    } catch (err) {
      console.error("❌ Error generating roadmap:", err);
      setRoadmap([{ phase: "Error", skills: ["Failed to fetch roadmap. Try again."] }]);
    } finally {
      setLoading(false);
    }
  };

  // Auto-generate from ?goal=...&skills=...
  useEffect(() => {
    const qGoal = searchParams?.get("goal");
    const qSkillsRaw = searchParams?.get("skills");
    if (!qGoal) return;
    const qSkills = normalizeSkills(qSkillsRaw);
    setGoal(qGoal);
    if (qSkills) setSkills(qSkills);
    if (autoGeneratedRef.current) return;
    (async () => {
      if (!session?.user) {
        try {
          await signIn("guest", { redirect: false });
        } catch (e) {
          console.warn("Guest sign-in failed:", e);
        }
      }
      await new Promise((r) => setTimeout(r, 250));
      await generateRoadmap(qGoal, qSkills);
      autoGeneratedRef.current = true;
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams, session?.user]);

  // PDF logic (unchanged)
  const downloadPDF = async () => {
    if (!roadmap || roadmap.length === 0) {
      alert("Generate a roadmap first.");
      return;
    }
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    let y = 40;
    doc.setFontSize(18);
    doc.text("CareerForge - Career Roadmap", 40, y);
    y += 20;
    doc.setFontSize(13);
    doc.text(`Goal: ${goal || "N/A"}`, 40, y);
    y += 14;
    doc.text(`Current Skills: ${skills || "N/A"}`, 40, y);
    y += 20;
    roadmap.forEach((step) => {
      doc.setFontSize(15);
      doc.text(step.phase, 40, y);
      y += 14;
      doc.setFontSize(12);
      step.skills.forEach((s) => {
        const lines = doc.splitTextToSize(`• ${s}`, 480);
        doc.text(lines, 60, y);
        y += lines.length * 14;
        if (resources[s]) {
          resources[s].forEach((r) => {
            const linkLines = doc.splitTextToSize(`   ▶ ${r.title} (${r.url})`, 460);
            doc.text(linkLines, 80, y);
            y += linkLines.length * 14;
          });
        }
        y += 6;
      });
      y += 8;
      if (y > 760) {
        doc.addPage();
        y = 40;
      }
    });
    doc.save(`${(goal || "career-roadmap").replace(/\s+/g, "-").toLowerCase()}.pdf`);
  };

  // Save to Dashboard (redirect to dashboard home)
  const handleAddRoadmap = async () => {
    if (!roadmap || roadmap.length === 0) {
      setSaveMessage("Generate a roadmap before saving.");
      return;
    }
    const name = roadmapName?.trim() || `${goal || "My"} Roadmap`;
    setSaving(true);
    setSaveMessage(null);
    const skillsArr = skills
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    const toSave = {
      name,
      skills: skillsArr,
      payload: {
        roadmap,
        resources,
        metadata: { goal, createdAt: new Date().toISOString() },
        progress: null,
      },
    };
    try {
      await addRoadmap(toSave as any);
      await refresh();
      setSaveMessage("Roadmap saved. Redirecting to Dashboard...");
      setTimeout(() => router.push(`/dashboard`), 600);
    } catch (err) {
      console.error("Failed to save roadmap:", err);
      try {
        const existing = JSON.parse(localStorage.getItem("careerforge_roadmaps") || "[]");
        const id = `local_${Date.now()}`;
        const toSaveLocal = { id, name, goal, skills: skillsArr, roadmap, resources, createdAt: new Date().toISOString() };
        existing.unshift(toSaveLocal);
        localStorage.setItem("careerforge_roadmaps", JSON.stringify(existing));
        setSaveMessage("Saved locally (fallback). Redirecting to Dashboard...");
        setTimeout(() => router.push(`/dashboard`), 600);
      } catch {
        setSaveMessage("Failed to save roadmap. Try again.");
      }
    } finally {
      setSaving(false);
    }
  };

  const canDownloadPdf = !!(session?.user && !session.user.isGuest);

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Career Roadmap Generator</h1>

      <div className="mb-4">
        <label className="block mb-2 font-medium">Career Goal</label>
        <input
          type="text"
          value={goal}
          onChange={(e) => setGoal(e.target.value)}
          className="border rounded p-2 w-full"
          placeholder="e.g. Web Developer, Data Scientist"
        />
      </div>

      <div className="mb-4">
        <label className="block mb-2 font-medium">Current Skills</label>
        <input
          type="text"
          value={skills}
          onChange={(e) => setSkills(e.target.value)}
          className="border rounded p-2 w-full"
          placeholder="e.g. Python, HTML, DSA (comma-separated)"
        />
      </div>

      <div className="flex gap-3 mb-4">
        <button
          onClick={() => generateRoadmap()}
          disabled={loading}
          className={`px-4 py-2 rounded text-white ${loading ? "bg-gray-400 cursor-not-allowed" : "bg-blue-600 hover:bg-blue-700"}`}
        >
          {loading ? "Generating..." : "Generate Roadmap"}
        </button>

        {canDownloadPdf ? (
          <button onClick={downloadPDF} className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">
            Download PDF
          </button>
        ) : (
          <div className="text-sm text-gray-500 self-center">Log in to download roadmap PDF</div>
        )}
      </div>

      {loading && <p className="mt-4">⚡ Generating roadmap...</p>}

      {!loading && roadmap.length > 0 && (
        <div className="mt-6 space-y-4">
          <Accordion type="single" collapsible value={expanded ?? undefined} onValueChange={(v) => setExpanded(v ?? null)} className="w-full">
            {roadmap.map((step, i) => (
              <AccordionItem key={i} value={`phase-${i}`}>
                <AccordionTrigger className="text-xl font-semibold">{step.phase}</AccordionTrigger>
                <AccordionContent>
                  <ul className="list-disc list-inside space-y-4">
                    {step.skills.map((s, j) => (
                      <li key={j} className="flex justify-between items-start gap-4">
                        <div>
                          <p className="font-medium">{s}</p>
                        </div>

                        <div className="ml-4">
                          <ul className="ml-4 list-none">
                            {resources[s]?.map((r: Resource, idx: number) => (
                              <li key={idx}>
                                <a href={r.url} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                                  ▶ {r.title}
                                </a>
                              </li>
                            ))}
                          </ul>
                        </div>
                      </li>
                    ))}
                  </ul>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>

          <div className="mt-4 border-t pt-4 flex flex-col gap-3">
            <label className="text-sm font-medium">Roadmap name</label>
            <input
              type="text"
              value={roadmapName}
              onChange={(e) => setRoadmapName(e.target.value)}
              placeholder={`${goal || "My"} Roadmap`}
              className="border rounded p-2 w-full"
            />

            <div className="flex items-center gap-3">
              <button
                onClick={handleAddRoadmap}
                disabled={saving}
                className={`px-4 py-2 rounded text-white ${saving ? "bg-gray-400 cursor-not-allowed" : "bg-indigo-600 hover:bg-indigo-700"}`}
              >
                {saving ? "Saving..." : "Add Roadmap"}
              </button>

              {canDownloadPdf ? (
                <button onClick={downloadPDF} className="bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700">
                  Download PDF
                </button>
              ) : (
                <div className="text-sm text-gray-500 self-center">Log in to download roadmap PDF</div>
              )}
            </div>

            {saveMessage && <div className="text-sm text-gray-700">{saveMessage}</div>}
            {session?.user?.isGuest && <div className="text-sm text-yellow-600">Log in to save roadmaps to your account.</div>}
          </div>
        </div>
      )}
    </div>
  );
}
